name: Run Auralix

on:
  schedule:
    - cron: "30 4 * * *"  # ⏰ 4:30 AM UTC daily
  workflow_dispatch:       # ✅ Also manually triggerable
jobs:
  run-flask-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set environment variables
        run: |
          echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" >> $GITHUB_ENV
          echo "SLACK_BOT_TOKEN=${{ secrets.SLACK_BOT_TOKEN }}" >> $GITHUB_ENV
          echo "SLACK_CHANNEL_ID=${{ secrets.SLACK_CHANNEL_ID }}" >> $GITHUB_ENV
          echo "SLACK_WEBHOOK_URL=${{ secrets.SLACK_WEBHOOK_URL }}" >> $GITHUB_ENV
          echo "NOTION_TOKEN=${{ secrets.NOTION_TOKEN }}" >> $GITHUB_ENV
          echo "PARENT_PAGE_ID=${{ secrets.PARENT_PAGE_ID }}" >> $GITHUB_ENV
          echo "TOKEN_GITHUB=${{ secrets.TOKEN_GITHUB }}" >> $GITHUB_ENV
          echo "REPO_OWNER=${{ secrets.REPO_OWNER }}" >> $GITHUB_ENV
          echo "REPO_NAME=${{ secrets.REPO_NAME }}" >> $GITHUB_ENV

      - name: Run Auralix
        working-directory: backend/dailysync
        run: |
          python flask_app.py
